/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrm.modules.core2.front_office;

import hrm.modules.core2.billing.Billing;
import hrm.modules.core2.housekeeping.Housekeeping;
import hrm.shared.GuestFolio;
import hrm.shared.RoomInfo;
import javax.swing.JOptionPane;

/**
 *
 * @author DelaTorreNelson
 */
public class RoomTiles extends javax.swing.JPanel {
    public String status = null;
    
    public RoomTiles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        roomUtility = new javax.swing.JPopupMenu();
        mnu_housekeeping = new javax.swing.JMenuItem();
        mnu_maintenance = new javax.swing.JMenuItem();
        mnu_facility = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lbl_room_no = new javax.swing.JLabel();
        lbl_guest_name = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_guest_id1 = new javax.swing.JLabel();
        lbl_guest_id = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_check_in = new javax.swing.JLabel();
        lbl_check_in1 = new javax.swing.JLabel();
        lbl_check_out = new javax.swing.JLabel();

        mnu_housekeeping.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        mnu_housekeeping.setText("Housekeeping");
        mnu_housekeeping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_housekeepingActionPerformed(evt);
            }
        });
        roomUtility.add(mnu_housekeeping);

        mnu_maintenance.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        mnu_maintenance.setText("RoomMaintenance");
        roomUtility.add(mnu_maintenance);

        mnu_facility.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        mnu_facility.setText("Facilities");
        roomUtility.add(mnu_facility);

        jMenu2.setText("jMenu2");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jMenuItem4.setText("jMenuItem4");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jMenuItem5.setText("jMenuItem5");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jMenuItem6.setText("jMenuItem6");
        jMenu2.add(jMenuItem6);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");
        jMenu2.add(jCheckBoxMenuItem1);

        roomUtility.add(jMenu2);

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setComponentPopupMenu(roomUtility);
        setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        setFocusCycleRoot(true);
        setFocusTraversalPolicyProvider(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);

        lbl_room_no.setBackground(new java.awt.Color(0, 173, 0));
        lbl_room_no.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_room_no.setForeground(new java.awt.Color(255, 255, 255));
        lbl_room_no.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_room_no.setText("1");
        lbl_room_no.setToolTipText(status);
        lbl_room_no.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_room_no.setMaximumSize(getPreferredSize());
        lbl_room_no.setMinimumSize(getPreferredSize());
        lbl_room_no.setOpaque(true);
        lbl_room_no.setToolTipText(this.status);
        lbl_room_no.setPreferredSize(new java.awt.Dimension(32, 32));
        lbl_room_no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_room_noMouseClicked(evt);
            }
        });

        lbl_guest_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_guest_name.setForeground(java.awt.Color.darkGray);
        lbl_guest_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_guest_name.setText("Mr. John Doe");
        lbl_guest_name.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_guest_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_guest_nameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_room_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_guest_name, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_room_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lbl_guest_name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 2);
        add(jPanel1, gridBagConstraints);

        jPanel2.setOpaque(false);

        lbl_guest_id1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_guest_id1.setForeground(java.awt.Color.darkGray);
        lbl_guest_id1.setText("ID:");

        lbl_guest_id.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_guest_id.setForeground(java.awt.Color.darkGray);
        lbl_guest_id.setText("1234234456409");

        jPanel3.setOpaque(false);

        lbl_check_in.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_check_in.setForeground(java.awt.Color.darkGray);
        lbl_check_in.setText("12-03-17");

        lbl_check_in1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_check_in1.setForeground(java.awt.Color.darkGray);
        lbl_check_in1.setText(" to");

        lbl_check_out.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_check_out.setForeground(java.awt.Color.darkGray);
        lbl_check_out.setText("12-04-17");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(lbl_check_in)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_check_in1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_check_out)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_check_in1)
                    .addComponent(lbl_check_in)
                    .addComponent(lbl_check_out))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_guest_id1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_guest_id, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_guest_id)
                    .addComponent(lbl_guest_id1))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void mnu_housekeepingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_housekeepingActionPerformed
        Housekeeping houseKeeping = new Housekeeping();
        
        houseKeeping.setVisible(true);
    }//GEN-LAST:event_mnu_housekeepingActionPerformed

    private void lbl_guest_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_guest_nameMouseClicked
        GuestFolio guestFolio = new GuestFolio();
        guestFolio.setTitle(lbl_guest_name.getText() + "'s Folio");
        guestFolio.setVisible(true);        
    }//GEN-LAST:event_lbl_guest_nameMouseClicked

    private void lbl_room_noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_room_noMouseClicked
        RoomInfo roomInfo = new RoomInfo();
        roomInfo.setTitle("Room 00"+lbl_room_no.getText()+" info ");
        roomInfo.setVisible(true);        
    }//GEN-LAST:event_lbl_room_noMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
        
        
        if(this.status.equals("available")){
            CheckIn checkIn = new CheckIn();
            checkIn.setVisible(true);            
        }if(this.status.equals("occupied")){
            Billing bill = new Billing();
            bill.setTitle(lbl_guest_name.getText() + "'s Bill");
            bill.setVisible(true);                    
        }

    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenuItem jMenuItem4;
    public javax.swing.JMenuItem jMenuItem5;
    public javax.swing.JMenuItem jMenuItem6;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lbl_check_in;
    public javax.swing.JLabel lbl_check_in1;
    public javax.swing.JLabel lbl_check_out;
    public javax.swing.JLabel lbl_guest_id;
    public javax.swing.JLabel lbl_guest_id1;
    public javax.swing.JLabel lbl_guest_name;
    public javax.swing.JLabel lbl_room_no;
    public javax.swing.JMenuItem mnu_facility;
    public javax.swing.JMenuItem mnu_housekeeping;
    public javax.swing.JMenuItem mnu_maintenance;
    public javax.swing.JPopupMenu roomUtility;
    // End of variables declaration//GEN-END:variables
}
